# Generated by Django 4.1 on 2022-08-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="characters",
            field=models.CharField(default="No Value", max_length=50),
        ),
        migrations.AddField(
            model_name="data",
            name="paragraphs",
            field=models.CharField(default="No Value", max_length=50),
        ),
        migrations.AddField(
            model_name="data",
            name="sentences",
            field=models.CharField(default="No Value", max_length=50),
        ),
        migrations.AddField(
            model_name="data",
            name="words",
            field=models.CharField(default="No Value", max_length=50),
        ),
    ]
